export enum ESectionFields {
  Title = 'title',
  OrderIndex = 'orderIndex',
  CalculationMethod = 'calculationMethod',
  AmountType = 'amountType',
  CalculationType = 'calculationType',
  ItemsStartIndex = 'itemsStartIndex',
  TotalActualsSum = 'totalActualsSum',
  DonePercentage = 'donePercentage',
  WorkspaceRef = 'workspaceRef',
  ItemPrice = 'itemPrice',
  ItemsCount = 'itemsCount',
  TotalSum = 'totalSum',
  Description = 'description',
  SubTotal = 'subTotal',
}
