export enum EAccountFields {
  Title = 'title',
  Description = 'description',
  PeriodUnit = 'periodUnit',
  PeriodFrequancey = 'periodFrequancey',
  Period = 'period',

  PeriodNumber = 'periodNumber',
  ConfirmFlow = 'confirmFlow',
  AccountStage = 'accountStage',
  BillingDate = 'billingDate',

  TotalSections = 'totalSections',
  TotalAdditions = 'totalAdditions',
  TotalSubtractions = 'totalSubtractions',
  AccumulatedTotal = 'accumulatedTotal',
  DelayPercentage = 'delayPercentage',
  TotalDelay = 'totalDelay',
  DelayRelease = 'delayRelease',
  TotalAccountToPay = 'totalAccountToPay',
  IndexedPercent = 'indexedPercent',
  TotalIndexed = 'totalIndexed',
  TotalAfterIndexed = 'totalAfterIndexed',
  VatPercent = 'vatPercent',
  TotalVAT = 'totalVAT',
  TaxPercent = 'taxPercent',
  TotalTax = 'totalTax',
  TotalToPay = 'totalToPay',
}
