export enum EContractFields {
  Title = 'title',
  Description = 'description',
  VendorRef = 'vendorRef',
  ActualsStatus = 'actualsStatus',
  BudgetbudgetaryItem = 'budgetbudgetaryItem',
  TotalAgreementSum = 'totalAgreementSum',
  PaymentDelay = 'paymentDelay',
  DelayPercentage = 'delayPercentage',
  Status = 'status',
  IsIndexed = 'isIndexed',
  IndexedFactor = 'indexedFactor',
  IndexedPercentage = 'indexedPercentage',
  CalculationMethod = 'calculationMethod',
  SWorkDate = 'sWorkDate',
  NumberOfPeriods = 'numberOfPeriods',
  EWorkDate = 'eWorkDate',
  ContractType = 'contractType',
  DonePercentage = 'donePercentage',
  TotalActualsSum = 'totalActualsSum',
  CurrentAccountPeriod = 'currentAccountPeriod',
}
