export enum ProjectFields {
  Title = 'title',
  Address = 'address',
  ProjectType = 'projectType',
  SDate = 'sDate',
  EDate = 'eDate',
  NumberOfPeriods = 'numberOfPeriods',
  Description = 'description',
  Manager = 'manager',
  SeniorManager = 'seniorManager',
  Entrepreneur = 'entrepreneur',
  Executor = 'executor',
  NumberOfBuildings = 'numberOfBuildings',
  Basements = 'basements',
  NumberOfApatrments = 'numberOfApatrments',
  Status = 'status',
  TotalActualsSum = 'totalActualsSum',
  TotalAgreementSum = 'totalAgreementSum',
  DonePercentage = 'donePercentage',
}
